### ISSUE TITLE
unnecessary which

### ISSUE THREAD

**Issue by jakejh** [jakejh/metapredict#13]
https://github.com/hugheylab/metapredict/blob/b2d87cb9c0cbfd19b6c5953c832bc95c31c07606/R/metapredict_merge.R#L15

**Comment by JSchoenbachler** [comment]
Posted the comment to the wrong issue, moving to other issue and reopening for now.

**Comment by JSchoenbachler** [comment]
Fixed in this commit c2a8a2d9e88005a3c7275e3f108bdb801775a350
