### ISSUE TITLE
foreach loop not parallelized

### ISSUE THREAD

**Issue by jakejh** [jakejh/metapredict#15]
This is why we wanted to use the doFuture package.

https://github.com/hugheylab/metapredict/blob/b2d87cb9c0cbfd19b6c5953c832bc95c31c07606/R/metapredict_process.R#L124

**Comment by JSchoenbachler** [comment]
I had removed this awhile ago, and I'm remembering why now. I was debugging and the code seemed to be taking significantly longer....I re-added this to this line of code and the code doesn't even really seem to be running. I will continue to look into this.

**Comment by JSchoenbachler** [comment]
Figured it out, done in this commit: 2b993c6364f730451d7ffedb6e5f967aaecb1149
