### ISSUE TITLE
mapping still only a data.frame

### ISSUE THREAD

**Issue by jakejh** [jakejh/metapredict#16]
Later functions could fail if they assume `mapping` is always a data.table. Check that all the `getMapping...` functions return a data.table.

https://github.com/hugheylab/metapredict/blob/b2d87cb9c0cbfd19b6c5953c832bc95c31c07606/R/metapredict_process.R#L93

**Comment by JSchoenbachler** [comment]
Fixed in commit b52c1ee8a4170ecf65278a4d767228b40e8356fc
