### ISSUE TITLE
Functions to test and specific things to test

### ISSUE THREAD

**Issue by JSchoenbachler** [jakejh/metapredict#21]
Here are all the functions to test. Additionally, if I feel the testing requires more than simply running the function and expecting outputs to match up I have included sub-bullet points highlighting notes of such:

- metapredict_confusion
    - calcConfusionCv
    - calcConfusionValidation
- metapredict_merge
    - mergeMatchStudyData
        - Duplicate studies in input
    - mergeStudyData
        - Validate error when sampleNames has sample not found in sample column
        - Test inputs with single and multiple batches
- metapredict_plot
    - plotCoefficients
        - Force `ncol(coefDt) == 2` in inputs
    - plotExpressionHeatmap
        - Toggle `clusterTogether`
        - Toggle `geneIdOrder` as NA and not NA
    - plotClassProbsCv
        - Toggle `classLevels` as NA and not NA
        - Toggle `ggplotArgs` as NA and not NA
    - plotClassProbsValidation
- metapredict_predict
    - makeGlmnetArgs
    - metapredictCv
        - Pass `family` into `...` argument
        - Toggle `addlFeatureColnames` as NA and not NA
        - Toggle `foldid` as NA and not NA
    - metapredict
    - makeCoefDt
        - `coefResult` is list
            - `classLevels` Toggle NA
        - `coefResult` is not list
- metapredict_process
    - getGeneProbeMappingAffy
    - getGeneProbeMappingDirect
    - getGeneProbeMappingAnno
        - `dbName == 'org.Hs.egUNIGENE2EG'`
    - calcExprsByGene
    - getStudyData
        - This one is tricky since there are so many platforms and differences.
            - Can we simplify the if statements?
            - Alternatively, we could add additional `isTesting` parameter we have used before to run/not run the method.
        - I think we should at least try to cover the `studyDataType` differences, then we can discuss approach to nested if statement.
        - Try to catch warnings:
            - Study not loaded, because platform is not currently supported
            - Imputing missing expressiong values
            - Study not loaded, because data type is not currently supported
    - getStudyDataList
    - extractExpressionData

**Comment by JSchoenbachler** [comment]
@jakejh Please review this and see if you have any comments or discrepancies on testing specifics!

**Comment by jakejh** [comment]
1. What's your specific plan for constructing the dataset to use for the tests?
2. In terms of priority, I would first make tests for functions in metapredict_process.R and metapredict_predict.R, since those are the most commonly used.
3. How do you suggest simplifying the `if` statements in `getStudyData`?

**Comment by JSchoenbachler** [comment]
1. I don't quite know for sure. I might have misunderstood, but I thought you were going to take a look at this list then we would discuss options. I know we just want to do a smaller set of data, so if we could use the study data from the vignettes but maybe filtered down to be significanly smaller.
2. Sounds good to me and like the easiest ones to test too, since you just have them go through most steps after giving some basic info.
3. I haven't thought about it too much, but as an example we could take lines 202-211 and simplify that to be an if statement with something like a named list like this: 
```
platToGene = list(GPL341 = 'ENTREZ_GENE_ID', GPL571 = 'ENTREZ_GENE_ID', GPL885 = 'GENE' ........)
if (platformInfo %in% names(platToGene)) {
    mapping = getGeneProbeMappingDirect(featureDt, geneColname = platToGene[[platformInfo]])}
```

**Comment by jakejh** [comment]
Re 1, I'm trying to understand what you actually intend to test, because just listing the function name is too vague.

Re 3, I like where you're going, but it has to account for all the variations. We might want to revise the `getSupportedPlatforms` function to return some or all of this information.

**Comment by JSchoenbachler** [comment]
1. By simply listing the function name, I mostly just mean we should test the function to make sure it gets the correct output (both in type and value).  If we decide on a small set of data to test with, we can just store the data at different points in the process to test the function with the already set up inputs. The functions listed with further details are essentially stating we should test specific things on those functions (warnings thrown, etc.).
3. I know there are a lot of variations, but I'm just hoping we could condense it some so we don't thoroughly test everything else in the package and end up with like 60% coverage because we didn't account for all the different platforms and study data types.
