### ISSUE TITLE
Use data.table instead of dplyr

### ISSUE THREAD

**Issue by JSchoenbachler** [jakejh/metapredict#6]
- [x] metapredict_confusion
- [x] metapredict_merge
- [x] metapredict_plot
- [x] metapredict_predict
- [x] metapredict_process

**Comment by JSchoenbachler** [comment]
@jakejh So far this has been great, just running into a few issues. The main one right now is that when I run the example script for the vignettes, I get to this line:

`ematList = extractExpressionData(esetList, sampleMetadata)`

When I get the error

` Error in { : task 1 failed - "invalid subscript type 'closure'" `
Traceback:
`4.
stop(simpleError(msg, call = expr)) `
`3.
e$fun(obj, substitute(ex), parent.frame(), e$data) `
`2.
foreach(studyName = names(esetList)) %do% {
    sampleNamesNow = as.data.frame(data.table(sampleMetadata)[which(study == 
        studyName), sample])
    keepIdx = colnames(esetList[[studyName]]) %in% sampleNamesNow ... at metapredict_process.R#428`
`1.
extractExpressionData(esetList, sampleMetadata) `

The weird thing is that this ONLY happens when I try to use the `extractExpressionData` function. If I take the variables and go into the function manually to run the logic, it works fine without issue.

Have you ever seen anything like this before?

**Comment by JSchoenbachler** [comment]
Also, metapredict_merge isn't done yet because I have to do the thing you sent last week to test it and it uses a weird grouping then ungrouping so I am working on that next.

**Comment by jakejh** [comment]
I'm not sure, but are you properly importing the `data.table` function for the package to use? Usually I get that error message when a function or variable isn't available or doesn't exist.

As an aside, the `which` is unnecessary. Read the documentation on the `i` argument.

**Comment by JSchoenbachler** [comment]
I was looking and I don't see where I could be doing something wrong, please let me know if I missed something:

DESCRIPTION file in Imports: https://github.com/hugheylab/metapredict/blob/0bbb657a6d79a882032b84bcf775872010c85968/DESCRIPTION#L24

metapredict_process at top and in function:
https://github.com/hugheylab/metapredict/blob/0bbb657a6d79a882032b84bcf775872010c85968/R/metapredict_process.R#L7
https://github.com/hugheylab/metapredict/blob/0bbb657a6d79a882032b84bcf775872010c85968/R/metapredict_process.R#L430

**Comment by JSchoenbachler** [comment]
@jakejh the weirdness continues...I was able to use `@import data.table` and it worked after I re-generated the NAMESPACE file (which Install and Restart wasn't doing....is that supposed to be that way?). But I ran into a different, weird issue....

When I get to the line
`plotExpressionHeatmap(fitResult, lambda, ematDiscovery, sampleMetadata, annoLevels,
                      annoColors, classLevels = classLevels, fontsize_row = 7)`
it gives me the following error:
`Error in foreach(classLevel = classLevels) %do% { : 
  could not find function "%do%"
`
I didn't change anything about the loop......it is as it was in the original package.

I also am STILL getting an error message saying that my R session quit unexpectedly and being forced to restart RStudio and a new R session before I am able to re-build/re-install the package.

Could this be something wrong with my RStudio? Have you ever had anything happen like this before?

**Comment by JSchoenbachler** [comment]
Nevermind. The RStudio commands to build and install were working weird (I think) because I didn't have the expression_data folder in vignettes for building the vignettes. I think this caused it not to build correctly and give me weird results. I fixed that and manually ran the build and install commands from the terminal, which worked and the outputs matched 100%.

**Comment by JSchoenbachler** [comment]
This has been finished, moving to closed to move onto other aspects!
